import Dashboard from "@/Components/Dashboard"
import "../globals.css";
import 'remixicon/fonts/remixicon.css'
import Dashbar from "@/Components/Dashbar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
      <body>
      <Dashboard/>
      <Dashbar/>
      {children}
      </body>
    </html>
  )
}
